version: '3'

networks:
  net:
    driver: bridge
services:
  db:
    image: postgres
    container_name: pollsdb
    # restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin1343
      POSTGRES_DB: pollsdb

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - pgdata:/data/postgres
      
  api:
    container_name: polls-api
    build:
        context: "./polls-backend/"
        dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
    ports:
      - "3080:3080"
    volumes:
      - ./polls-backend:/app
    depends_on:
       db: 
        condition: service_healthy
    links:
      - db

  frontend:
    build:
      context: "./polls-front"
      dockerfile: Dockerfile
      target: runner
    container_name: polls-front
    command: npm run dev

    environment:
      NODE_ENV: development

    volumes:
        - ./polls-front:/app

    ports:
      - "3000:3000"
    depends_on:
      - api
    links:
      - api

volumes:
  pgdata:
    driver: local
